<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC8-DX-6NNJH92" ignored="0" name="Test1" tests="1" failures="1" timestamp="18 Jul 2018 05:18:52 GMT" time="13.443" errors="0">
  <testcase name="newtest" time="13.414" classname="p1.Class">
    <failure type="java.lang.AssertionError" message="expected [Sign in to GitHub · GitHub] but found [GitHub]">
      <![CDATA[java.lang.AssertionError: expected [Sign in to GitHub · GitHub] but found [GitHub]
at p1.Class.newtest(Class.java:35)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- newtest -->
</testsuite> <!-- Test1 -->
